Repository AY2425S1-CS2103-F09-2/tp, pull requests merged in 2024-11, with the labels that each got.

#102 Update puml, DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/SortCommandSequenceDiagram.puml
Labels: priority.High

#113 Fix bugs in DG
  docs/DeveloperGuide.md
Labels: priority.Medium

#114 Fix bugs in UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.Medium

#139 Update AddressBookParser.java for case sensitivity
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Enhancement

#142 Update View command functionality
  src/main/java/seedu/address/logic/commands/BirthdayCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FavouriteCommand.java
  src/main/java/seedu/address/logic/commands/LogCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/ui/PersonDetails.java
  src/main/resources/view/PersonDetails.fxml
Labels: priority.High

#143 Update the current UG and DG to the specifications of V1.5
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Enhancement

#135 Fix alpha bugs for relevant features
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/BirthdayCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Birthday.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/BirthdayCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: severity.Medium, alpha-bug

#147 Update ModelClassDiagram.png
  docs/DeveloperGuide.md
  docs/images/ModelClassDiagram.png
Labels: priority.High

#150 enable text wrapping in GUI
  src/main/resources/view/PersonDetails.fxml
Labels: alpha-bug

#213 Add new sections to the UG
  docs/UserGuide.md
Labels: priority.High

#159 Add sequence diagram for favourite command and variation
  docs/diagrams/FavouriteCommandSequenceDiagram.puml
Labels: priority.Medium

#214 Fix log error message incomplete parameters
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/LogCommand.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: severity.High

#217 Add table of contents to both DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High

#219 Fix PED Bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
Labels: priority.High

#224 Update Help Window to reflect correct link
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.Medium

#223 Fix PE Dry Run bugs
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/BirthdayCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: severity.High

#225 Update User Guide and Developer Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/helpMessage.png
Labels: priority.High

#239 Fix bugs in Use Cases in Developer Guide
  docs/DeveloperGuide.md
Labels: priority.High, severity.High

#243 Update documentation for product
  docs/_sass/minima/_base.scss
Labels: priority.Medium

#248 Fix bug in Favourite Command sequence diagram
  docs/diagrams/FavouriteCommandSequenceDiagram.puml
  docs/images/FavouriteCommandSequenceDiagram.png
Labels: priority.Medium

#249 Update Favourite Sort sequence diagram
  docs/diagrams/favouriteSort.puml
  docs/images/favouriteSort.png
Labels: priority.Medium
